wp-graphql/wp-graphql-woocommerce

.travis.yml

Updates `.travis.yml` script to notify `coveralls.io` 
…
…
**Operating System:** Ubuntu 18.04 …

after_success script added

---

src/class-actions.php
src/connection/class-products.php
src/data/connection/class-product-connection-resolver.php
src/model/class-product-variation.php
src/type/enum/class-product-type.php
src/type/object/class-product-type.php
src/type/object/class-product-variation-type.php
vendor/composer/autoload_classmap.php
vendor/composer/autoload_static.php

Uses WC_Product_Query instead of WP_Query. Adds support for custom Product data stores, however pagination functionality will to still have to filtered in order to work properly.
Implements `ProductTypesEnum` for resolve product type. values are filterable through the `graphql_product_types_enum` hook.
… …

Replaces WP_Query to WC_Product_Query in Product connections

---

src/model/class-crud-cpt.php
src/model/class-customer.php
src/model/class-order-item.php
src/model/class-shipping-method.php
src/model/class-tax-rate.php

Adds hooks for filtering the `restricted_cap` property used in Model classes. The naming convention goes `{post_type}_restricted_cap` for types extending `Crud_CPT` and `{node_type}_restricted_cap` for all others. For example the hook for the Customer model is named `customer_restricted_cap`.
#51  …

Adds "*_restricted_cap" filters

---

includes/class-actions.php
includes/data/mutation/class-order-mutation.php
includes/mutation/class-order-create.php
includes/mutation/class-order-update.php
includes/type/input/class-fee-line-input.php
includes/type/input/class-line-item-input.php
includes/type/input/class-shipping-line-input.php
tests/wpunit/OrderMutationsTest.php
vendor/composer/autoload_classmap.php
vendor/composer/autoload_static.php

Implements `updateOrder` mutation, `shop_coupon` post-type `edit-post` cap required for use.
```
mutation updateOrder( $input: UpdateOrderInput! ) {
updateOrder( input: $input ) {
clientMutationId
order {
OrderType fields
}
}
}
```
`...`[`CreateOrderInput`](https://github.com/wp-graphql/wp-graphql-woocommerce/pull/97)` fields,`
```
'id'           => array(
'type'        => 'ID',
'description' => __( 'Order global ID.', 'wp-graphql-woocommerce' ),
), …
```

updateOrder mutation

---

includes/class-actions.php
includes/data/mutation/class-order-mutation.php
includes/model/class-crud-cpt.php
includes/model/class-order.php
includes/mutation/class-order-create.php
includes/mutation/class-order-delete.php
includes/mutation/class-order-update.php
tests/_support/Helper/crud-helpers/order.php
tests/wpunit/OrderMutationsTest.php
vendor/composer/autoload_classmap.php
vendor/composer/autoload_static.php

Implements `deleteOrder` mutation. User cap requirements are the same and `createOrder` and `updateOrder`.
```
mutation deleteOrder( $input: DeleteOrderInput! ) {
DeleteOrder( input: $input ) {
clientMutationId
order {
...OrderType fields
}
}
}
```
```
'id'      => array(
'type'        => 'ID',
'description' => __( 'Order global ID', 'wp-graphql-woocommerce' ),
),
'orderId' => array(
'type'        => 'Int',
'description' => __( 'Order WP ID', …
```

deleteOrder mutation

---

bin/install-wp-tests.sh
includes/type/object/class-product-type.php
tests/_support/Helper/crud-helpers/product.php
tests/wpunit/ProductQueriesTest.php

Adds `slug` and `sku` arguments to `productBy` query, with updated tests.
```
query ( $slug: String, $sku: String ) {
productBy( slug: $slug, sku: $sku ) {
...product fields
}
}
```
…
Any other …

Query products by slug and sku

---

includes/class-filters.php

When `define( 'NO_QL_SESSION_HANDLER', true);` is set. WooCommerce falls back to the default session handler for GraphQL requests. This is meant to allow for use of cookie sessions managed by `WC_Session_Handler` instead of the custom session header managed by the `QL_Session_Handler` class (the default) on GraphQL requests.
…
Any relevant logs, error output, GraphiQL …

Adds NO_QL_SESSION_HANDLER flag

---

includes/class-actions.php
includes/mutation/class-order-delete-items.php
includes/type/input/class-fee-line-input.php
tests/wpunit/OrderMutationsTest.php
vendor/composer/autoload_classmap.php
vendor/composer/autoload_static.php

Implements `deleteOrderItems` mutation. 
*NOTE: User cap requirements are the same and `createOrder` and `updateOrder`.*
```
mutation deleteOrderItems( $input: DeleteOrderItemsInput! ) {
DeleteOrderItems( input: $input ) {
clientMutationId
order {
...order fields
}
}
}
```
```
'clientMutationId' => array(
'type'        => array( 'non_null' => 'String' ),
'description' => __( 'Unique ID for mutation', 'wp-graphql-woocommerce' ),
),
'id'      => array(
'type' …
```

deleteOrderItems mutation

---

includes/model/class-product.php
includes/type/object/class-product-type.php
tests/_support/Helper/Wpunit.php
tests/_support/Helper/crud-helpers/product.php
tests/wpunit/ProductQueriesTest.php

…cription".
Adds `format` argument to description fields. It functions identically to **WPGraphQL**'s CPT content fields. Users must have the capability for editing products in order to retrieve the raw descriptions straight from the database, same as CPT-based types.
```
query ( $id: ID!, $format: PostObjectFieldFormatEnum ) {
product(id: $id) {
description(format: $format)
shortDescription(format: $format)
}
}
```
`PostObjectFieldFormatEnum` is an …

"format" arg added to Product description fields

---

includes/data/connection/class-product-connection-resolver.php

Add hook for filtering the default catalog visibility tax query used in `Product` connections for non-administrator request.
```
function show_all_products( $default_visiibility, $query_args, $source, $args, $context, $info ) {
if( 'allProducts' === $info->fieldName ) {
$default_visibility = null;
}
return $default_visibility;
}
add_filter( 'graphql_product_connection_catalog_visibility', 'show_all_products', 10, 6 );
```
Does this close any currently open …

"product_connection_catalog_visibility" hook implemented.

---

includes/class-woocommerce-filters.php

- x] Make sure you are making a pull request against the **develop branch** (left side). Also you should start *your branch* off *our develop*.
Adds escape hatch that prevents `QL_Session_Handler` from being used on any request not made to the GraphQL endpoint, (by default its `/graphql`). 
This includes query made uses the **GET** method *i.e. /graphql?query={...}*.
The `QL_Session_Handler` is designed to only update and send a response header after …

Escape hatch added on non-GraphQL requests.

---

includes/data/mutation/class-cart-mutation.php
includes/mutation/class-cart-add-fee.php
includes/mutation/class-cart-add-item.php
includes/mutation/class-cart-apply-coupon.php
includes/mutation/class-cart-empty.php
includes/mutation/class-cart-remove-coupons.php
includes/mutation/class-cart-remove-items.php
includes/mutation/class-cart-update-item-quantities.php
includes/mutation/class-cart-update-shipping-method.php

Adds `cart` field to all cart mutation output types.
```
mutation {
addToCart(input: { productId: 1, quantity: 2 }) {
clientMutationId
cartItem {
key
}
cart {
subtotal
}
}
```
#192
Any other …

"cart" field add to mutation output.

---

includes/model/class-product-variation.php
includes/model/class-product.php
tests/_support/Helper/crud-helpers/product.php

This adds a layer of security on some `Product` fields to prevent the leakage of sensitive data.
- `totalSales`
- `catalogVisibility`
#210 
…
Where has this …

Updates some product fields' access levels

---

includes/mutation/class-customer-register.php

This just makes sure that if someone wants to enable automatic password generation, they can do so via WooCommerce settings and still be able to register customers through this endpoint.
Nope
…
MacOS
**WordPress Version:** …

allow optional password creation for registerCustomer

---

includes/connection/class-cart-items.php
includes/data/class-factory.php
includes/data/connection/class-cart-item-connection-resolver.php
includes/data/connection/class-product-connection-resolver.php
tests/_support/Helper/crud-helpers/cart.php
tests/wpunit/CartQueriesTest.php

Enhances the `Cart` to `CartItem` connection.
- adds `itemCount` field. Number of items in the cart. See example below.
- adds `productCount` field. Number of different products in the cart. See example below.
- `needShipping` whereArg implemented. See example below.
- Pagination implemented. See example below.
```
query ($first: Int, $last: Int, $before: String, $after: String, $needShipping: Boolean) {
cart {
contents(first: $first, last: $last, before: …
```

Pagination implemented on cart connection

---

includes/connection/class-tax-rates.php
includes/data/connection/class-tax-rate-connection-resolver.php
tests/_support/Helper/crud-helpers/tax-rate.php
tests/wpunit/TaxRateQueriesTest.php

- Adds `postCode` and `postCodeIn` whereArgs to the `taxRates` query.
```
query ( $class: TaxClassEnum, $postCode: String, $postCodeIn: [String] ) {
taxRates( where: { class: $class, postCode: $postCode, postCodeIn: $postCodeIn } ) {
nodes {
id
}
}
}
```
```
'class'      => array(
'type'        => 'TaxClassEnum',
'description' => __( 'Sort by tax class', 'wp-graphql-woocommerce' ),
),
'postCode'   => array(
'type'        => 'String',
'description' => __( …
```

TaxRate connection improvements

---

includes/mutation/class-checkout.php
tests/acceptance/NewCustomerCheckingOutCept.php
tests/wpunit/CheckoutMutationsTest.php

Updates the `checkout` mutation's `shippingMethod` field to be a list of strings. So it can be properly set to the [session](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/develop/includes/data/mutation/class-checkout-mutation.php#L194-L198) before [order creation](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/develop/includes/data/mutation/class-checkout-mutation.php#L517). …

"shippingMethod" field type changed to [String].

---

includes/class-jwt-auth-schema-filters.php

The presence of the `WPGRAPHQL_JWT_AUTHENTICATION_VERSION` constant is not a guarantee the JWT plugin will be present. Checking if the plugin class is present is more reliable than the constant.

Changing how we verify the JWT plugin

---

includes/data/mutation/class-checkout-mutation.php

1. Checkout_Mutation::$logged_in_customer should be a static variable as shown 
https://github.com/wp-graphql/wp-graphql-woocommerce/blob/01df7b879b765f8cdbe90429309e0032fcb5f6aa/includes/data/mutation/class-checkout-mutation.php#L668
2. Namespace of WC_Customer is incorrect.
https://github.com/wp-graphql/wp-graphql-woocommerce/blob/01df7b879b765f8cdbe90429309e0032fcb5f6aa/includes/data/mutation/class-checkout-mutation.php#L669
Does this close any currently …

Fixed : missing static keyword for static variable

---

.github/workflows/testing-integration.yml
includes/data/class-factory.php
includes/data/loader/class-wc-cpt-loader.php
tests/_support/Helper/crud-helpers/cart.php
tests/wpunit/CartMutationsTest.php
tests/wpunit/CartQueriesTest.php
tests/wpunit/CheckoutMutationTest.php
tests/wpunit/MetaDataQueriesTest.php
tests/wpunit/PaymentGatewayQueriesTest.php

Adds a conditional to the Stripe checkout tests that will skip the tests if no Stripe API test keys have been provided.
…
… …

Skip conditional added to stripe test

---

includes/type/object/class-order-type.php

`WPGraphQL\WooCommerce\Mode\Order` doesn't have `parent` field, instead `parent_id` should be used to access order's parent id in `Order` type.
https://github.com/wp-graphql/wp-graphql-woocommerce/blob/14f5316a976fd8ad38cf0e80a76a9e5d0836653c/includes/model/class-order.php#L256-L258
-----------------------------------------
#303  …

Fixed : #303

---

includes/model/class-order.php

- changes "downloadableItem" to "downloadable_item" is the `allowed_restricted_fields` list in the **Order** model to make the model field name.
…
…
Where …

Fixes downloadableItems accessibility bug.

---

includes/connection/class-products.php

Remove a undefined codecept_debug() function that causes server error when querying the `variations` field.
#342

Remove undefined codecept_debug() function

---

includes/connection/class-wc-terms.php

The current implementation `$source->{"$taxonomy}_ids"}` returns null, which results in all TermObjects getting returned, not just the connected ones.
`$tax_object` is an instance of `WP_Term`. We can use the `attributes` array of the `$source` - which returns an array of `WC_Product_Attribute` - to collect the connected ids to properly set the query args.
#345 
See the related issue. …

Return connected TermObjects from the PostObjectType

---

includes/connection/class-wc-terms.php

Ensures that connections between all products and their terms are properly connected, not just product attributes.
The previous PR (#346) mistakenly assumed that all connections were attributes. What we should be grabbing is the terms instead of the attributes.
#348 
#345 
See issues.
**WooCommerce:** 3.6
**WordPress Version:** 5.2

Connect terms to their source

---

includes/type/object/class-product-types.php

Syntax error on line 262.
I remove last coma inside array_merge().
No
…
**Operating System:** Windows 10
**WordPress Version:** 5.5.1

Fix Syntax Error in php7.2 and 7.4

---

includes/connection/class-wc-terms.php

`get_the_terms` can return `false`, which causes errors when running anything other than an array in `wp_list_pluck`. Related to #363.
Fixes an `ErrorException Invalid argument supplied for foreach()` when we pass anything other than an array to `wp_list_pluck()` when connecting a term to a product.
#363 
See the issue.

Guard against false terms when plucking IDs

---

includes/connection/class-wc-terms.php

Prevents returning all data for a given taxonomy when it's not associated with a product. That way if an attribute is not associated with a given product, we return `null` instead of the first `n` terms of the the taxonomy.
#372 
See issue.
@kidunot89 perhaps I should get the term ids and return _before_ instantiating the `TermObjectConnectionResolver` class? That way we truly bail early.
WP: 5.5.3
WooCommerce: …

Guard against empty terms

---

includes/mutation/class-customer-register.php
tests/wpunit/CustomerMutationsTest.php

Extends #340 
- Adds `testRegisterMutationWithoutAnyInfo` test to the `CustomerMutationsTest` test case.
@HiepVu511 :point_up: Good work on this :+1: 
…
… …

Make the username field optional in registerCustomer mutation

---

includes/data/connection/trait-wc-cpt-loader-common.php

This PR allows multiple `orderby` arguments to be passed to the `WP_Query`. 
This PR addresses issue [#262](https://github.com/wp-graphql/wp-graphql-woocommerce/issues/262)
**Operating System:** `OSX` + `Docker`
**WordPress Version:** `5.5.3`

Allow multiple "orderby" fields

---

includes/data/connection/class-variation-attribute-connection-resolver.php
includes/type/object/class-cart-type.php
includes/type/object/class-variation-attribute-type.php
tests/_support/Helper/GraphQLE2E.php
tests/_support/Helper/crud-helpers/cart.php
tests/acceptance/ReturningCustomerSessionCept.php
tests/wpunit/CartMutationsTest.php
tests/wpunit/CartQueriesTest.php

- `CartItem` fields `product` and `variation` changed to one-to-one connections.
- `attributes` added as an edge field on the `variation` connection.
- Test added for new fields.
**Example**
```graphql
query ($key: ID!) {
cartItem(key: $key) {
key
product {
node {
id
databaseId
}
}
variation {
attributes {
id
attributeId
name
label
value
}
node {
id
databaseId
}
}
quantity
subtotal
subtotalTax
total
tax
}
}
``` …

Release v0.7.0

---

docs/config.js

This will fix the 'Edit on GitHub' button links throughout the docs app. The current Url 404s.
No

[Docs]: Fix 'Edit on GitHub' link

---

.github/workflows/continous-integration.yml
includes/data/mutation/class-customer-mutation.php
includes/mutation/class-customer-register.php
includes/mutation/class-customer-update.php
tests/wpunit/CustomerMutationsTest.php
vendor/composer/InstalledVersions.php
vendor/composer/installed.php

Allow Customer to include metadata in registerCustomer mutation and updateCustomer mutation
No
Metadata in registerCustomer mutation
Metadata in customers query
Metadata in updateCustomer mutation
Tell me if this enough and meet your …

implements metadata for customer register and update

---

includes/type/object/class-product-variation-type.php

Fixes an error when a variation product does not have an image. The resolver is too eager in that it doesn't check for the existence of the image_id before attempting to resolve. As a result, when a variation product does not have an image and is queried, the corresponding resolve_post_object will throw an error because it expects an int type as the first argument, not null.
#423

Variation image: guard against null image_id

---

includes/type/object/class-meta-data-type.php

- [✅ ] Make sure you are making a pull request against the **develop branch** (left side). Also you should start *your branch* off *our develop*.
- [✅ ] Make sure you are requesting to pull request from a **topic/feature/bugfix/devops branch** (right side). Don't pull request from your master!
- [❌ ] Have you ensured/updated that CLI tests to extend coverage to any new logic. Learn how to modify the tests [here](https://woographql.com/contributing/2-local-testing).
"extraData" expects a string but receives an array or object. This bugfix JSON encodes an array so a string is returned.
This might also …

JSON stringify string to match expectation of "extraData" on cartItem

---

includes/model/class-refund.php
includes/type/object/class-refund-type.php
tests/_support/Helper/crud-helpers/refund.php
tests/wpunit/RefundQueriesTest.php

Adds date field to refund object. Is needed if you for example create monthly sales reports and need to see when a particular refund was made. 
No
No
Thank you for developing this! It's an awesome solution for headless WC.
Where has this …

Added refund date field

---

composer.json
includes/connection/class-coupons.php
includes/connection/wc-cpt-connection-args.php
includes/data/connection/class-coupon-connection-resolver.php
tests/_support/TestCase/WooGraphQLTestCase.php
tests/wpunit/CouponQueriesTest.php
tests/wpunit/ProductQueriesTest.php
vendor/composer/ClassLoader.php
vendor/composer/InstalledVersions.php
vendor/composer/autoload_real.php
vendor/composer/installed.php

- **Coupon_Connection_Resolver** class deprecated and will be removed in release **v0.11.x**. The "PostObjectConnectionResolver" class and the hooks contained within are used in it's place. Any remaining unique code in-use has be relocated to the `class-coupons.php`. 
- **CouponQueriesTest.php` has be refactored to use the WPGraphQLTestcase library.  
…
Any relevant logs, …

"Coupon_Connection_Resolver" deprecated.

---

includes/utils/class-session-transaction-manager.php

This PR intends to add enhancements and bug fixes to the Session Transaction Manager. Specifically:
1. fix `null` value for `_customer_id` when setting/getting the transients. As is **all** transients are getting set to the same id. As a result, if one error occurs, that makes it an error for all subsequent requests.
2. fix `null` value when setting `$snapshot` in the transaction. `$snapshot` isn't used at the moment, but it's incorrectly getting set.
3. add a timing mechanism to prevent infinite loops after a mutation error. As is, if there's an error, the transaction hangs around and becomes stale. Subsequent request will keep looping over and over until the server crashes because …

Session Transaction Manager bugfixes and enhancements

---

bin/_env.sh
bin/_lib.sh
includes/class-type-registry.php
includes/type/interface/class-attribute.php
includes/type/object/class-cart-type.php
includes/type/object/class-simple-attribute-type.php
includes/type/object/class-variation-attribute-type.php
tests/wpunit/CartMutationsTest.php

Introduces 'simpleAttributes' edge field
```graphql
mutation( $input: AddToCartInput! ) {
addToCart(input: $input) {
cartItem {
product {
simpleVariations {
name
value
}
node {
databaseId
}
}
}
}
}
```
Resolves #517 
(If it’s long, please paste to https://ghostbin.com/ and …

CartItem Product edge field "simpleAttributes" implemented and tested.

---

includes/connection/class-coupons.php
includes/connection/class-orders.php

Access denied state for `coupon` and `order` connection altered to match standard set in WPGraphQL.
Resolves #516
… …

Fix: Access denied state for coupon and order connections.

---

includes/data/mutation/class-checkout-mutation.php

Passes an empty instance of `WP_Error` to the `woocommerce_after_checkout_validation` action hook. WooCommerce passes an error object as the second argument to the hook and several 3rd party plugins expect it to be provided. Dokan for example doesn't even check `is_wp_error` before calling `$errors->add()` resulting in runtime errors. 
Normally I'd expect plugin developers to know better, do better but in this case, the wp-graphql-woocommerce breaks from …

Fix: pass expected checkout validation WP_Error instance

---

includes/model/class-product.php

$prices['price'] doesn't exist as $prices variable has already been overwritten inside the switch case. This causes pricing to return null for all pricing fields (regular, sale, price) which are formatted as RAW.
Fixes raw pricing for variable products returning null.
Fixes #479 
None
None

Fix raw pricing returning null

---

includes/type/object/class-customer-type.php

Since the woocommerce session takes into account that a guest user session can generate a token, this should be exposable thru the customer sessionToken trait. 
No. …

feature: customer call returns session token for guest users

---

includes/utils/class-ql-session-handler.php

Currently when the wp-graphql-woocommerce plugin is activated I'm getting CORS errors during clientside queries. I've tracked the the problem down and I found out that the plugin is still using a deprecated function that causes it.
Since Woocommerce v5.3.0 the `nonce_user_logged_out` function used in the session handler is deprecated. This PR replaces that function with the new `maybe_update_nonce_user_logged_out`. 
Does this close any currently open …

Replace deprecated function nonce_user_logged_out

---

includes/utils/class-ql-session-handler.php

- Session token expiration set to 2 weeks from creation.
- If the token is used within a day of a expiration an update token is dispensed.
Fixes #519
…
Where …

fix: session expiration extended to 2 weeks

---

includes/mutation/class-order-update.php

Order status was not being updated. Use "update_status" method instead of "set_status".
- https://github.com/wp-graphql/wp-graphql-woocommerce/issues/562
…
… …

[Bugfix] Update order status

---

includes/utils/class-ql-session-handler.php

This PR only changes one method to another the suggested one.
https://woocommerce.wp-a2z.org/oik_api/WC_Cache_Helper::incr_cache_prefix/
No.
The error message:
[fatal error]: 'WC_Cache_Helper::incr_cache_prefix is <strong>deprecated</strong> since verion 3.9.0! Use …

fix: change deprecated incr_cache_prefix

---

includes/data/mutation/class-order-mutation.php

Fix Fee name not showing on the order when using the createOrder mutation.
Before
Always shows 'Fee' even tho the name input was passed
After
Show's the name passed through the name input. In this case 'Planting Fee'
…
(If it’s long, please paste to https://ghostbin.com/ and …

Fix Fee name not showing

---

.github/workflows/continous-integration.yml
access-functions.php
includes/type/object/class-order-item-type.php
tests/_support/Helper/GraphQLE2E.php
tests/_support/Helper/crud-helpers/order.php
tests/wpunit/CheckoutMutationTest.php
tests/wpunit/OrderItemQueriesTest.php
tests/wpunit/OrderMutationsTest.php

- `LineItem` fields' `product` and `variation` changed to connections to be consist with the `CartItem` type.
Fixes #478 
… …

feat: "product" and "variation" connections added to LineItem type

---

includes/mutation/class-cart-fill.php

PHP warnings in the `fillCart` mutation when `coupons` or `shippingMethods` is empty.
…
…
- …

fix: warnings in fillCart with empty coupons/shippingMethods

---

includes/data/mutation/class-checkout-mutation.php
tests/_support/Factory/CouponFactory.php
tests/wpunit/CheckoutMutationTest.php

- Cart now emptied after successful `checkout` mutation
- **CheckoutMutationTest** refactored
Closes #490 
… …

fix: Cart emptied after checkout

---

includes/model/class-wc-post.php

Corrects viewing capability for all WC post types.
Fixes #624 
…
- …

fix: is_post_private overrode in WC_Post model abstract class

---

includes/connection/class-coupons.php

Call to undefined function WPGraphQL\\WooCommerce\\Connection\\codecept_debug() appears when search coupons accessed
…
…
… …

Remove error when search coupons

---

includes/class-woocommerce-filters.php

Method WPGraphQL\Router::is_graphql_request to WPGraphQL\Router::is_graphql_http_request
- [v] Make sure you are making a pull request against the **develop branch** (left side). Also you should start *your branch* off *our develop*.
- [v] Have you ensured/updated that CLI tests to extend coverage to any new logic. Learn how to modify the tests [here](https://woographql.com/contributing/2-local-testing).
This PR only changes one method to another the …

Change deprecated method is_graphql_request

---

includes/connection/class-products.php

* `$post_type` must be an array when passed to `in_array()`
* Removes unused `$post_type_obj` variable.
Slack thread: https://wp-graphql.slack.com/archives/CJUBND25R/p1672096763874069
The Gatsby error log typically looked like this:
```JS
ERROR #11321  API.NODE.EXECUTION …
```

fix:`$post_type` must be an array when passed to `in_array()`

---

includes/connection/class-products.php

**What does this implement/fix?**
This PR implements a 'graphql_woocommerce_products_add_sort_fields' hook to add custom sort fields to products. Currently it is possible to add values using the 'Products_orderby_enum_values' hook, but because of the hardcoded switch that the current master branch has, all the custom added values are ignored.
**Does this close any currently open issues?**
#694
- **WooGraphQL Version:** 1.13.7
- **WPGraphQL Version:** 0.12.0
- **WordPress Version:** 6.1.1
- **WooCommerce Version:** 7.2.2

Add filter to add custom fields to product sort

---

composer.json
composer.lock
includes/connection/class-orders.php
tests/_support/Factory/OrderFactory.php
tests/wpunit/CustomerQueriesTest.php

Fixes Customer -> Order connection argument priority by prioritize the `customer ID` then the `billing email` for guest without a Customer ID.
Fixes #689 
… …

fix: Customer order connection args priority fixed.

---

includes/model/class-order.php

Makes the Order type's RAW format available to guest users.
Fixes #685 
Fixes #
…
- **WooGraphQL …

feat: Auth no longer needed for the raw order totals

---

includes/type/interface/class-product.php
includes/type/object/class-product-category-type.php
includes/type/object/class-product-variation-type.php

Fixes deprecation errors:
Updates usage of deprecated function.
…
> _PHP message: PHP Deprecated:  Function WPGraphQL\Data\DataSource::resolve_post_object is <strong>deprecated</strong> since version 0.8.4! Use Use $context->get_loader( 'post' )->load_deferred( $id ) instead. …

Updates deprecated DataSource::resolve_post_object

---

includes/class-core-schema-filters.php
includes/connection/class-products.php
tests/_support/Factory/ProductVariationFactory.php
tests/wpunit/ProductAttributeQueriesTest.php
tests/wpunit/ProductQueriesTest.php

WhereArgs are now consistent across all product connections.
Fixes #694 
…
- **WooGraphQL Version:** …

fix: Fixed all product connection filtering regressions

---

includes/model/class-product.php
tests/wpunit/QLSessionHandlerTest.php

It adds `wc_get_price_to_display` so the prices returned in the field include the appropriate taxes.
Rationele
The [patch in v0.12.1](https://github.com/wp-graphql/wp-graphql-woocommerce/commit/82e5e72ff9260a55a4430691b42a7401246ee93e) fixes the price field for SimpleProduct and other product type inherited it's definition of it. regularPrice and salePrice however were left untouched. 
This PR allows regularPrice and salePrice to include or exclude the tax as these are the prices meant to be displayed to the end user.
Slack discussion/thread. 
https://wp-graphql.slack.com/archives/CCYJRDN4A/p1675417354842819?thread_ts=1675273227.466449& …

Adds tax calculation to regular and sale prices.

---

includes/utils/class-ql-session-handler.php

Overwrites `set_customer_session_cookie` with a noop in the `QL_Session_Handler`
https://github.com/wp-graphql/wp-graphql-woocommerce/issues/709

Adds noop for set_customer_session_cookie.

---

includes/model/class-product.php

In this [commit ](https://github.com/wp-graphql/wp-graphql-woocommerce/commit/bde5fc5bbd0627abac41e66acf72abe649d9845d#diff-39f30bb249526aed8658884c4a8fc3064cfa2322b0b692f6353cdf24f6c7eabdR259), the arguments passed into the function `\wc_get_price_to_display` are incorrect. 
The function receives as a parameter the `$product` and an array `$args.` 
We are currently including the `$product` inside the `$args` array. 
https://woocommerce.github.io/code-reference/namespaces/default.html#function_wc_get_price_to_display
Additionally, this PR removes `\wc_get_price_to_display` from the `priceRaw` to be consistent with the other raw prices. 
Raw price should not be passed into functions such …

Fix wrong function args in sale price and remove wc_get_price_to_display from raw price.

---

composer.json
includes/type/enum/class-post-type-orderby-enum.php

Adds the value  "NAME"  to the "PostTypeOrderbyEnum" enumeration type. It's tied the `post_title` field of products.
Fixes #588 
… …

feat: "NAME" added to "PostTypeOrderbyEnum" values

---

includes/data/mutation/class-cart-mutation.php

The applyCoupon mutation is case sensitive, but coupons are not. This fixes trying to add a coupon code with lower case letters, such as `10off`. Previously you would get an error that the coupon doesn't exist because of mismatch in the case.
…
…
(If it’s long, please paste to …

fix case sensitive apply coupon mutation

---

includes/type/object/class-meta-data-type.php
includes/type/object/class-root-query.php
tests/wpunit/CouponQueriesTest.php

- Returns flatten array meta values bypassing the array to string conversion array.
- As shop-level cap check to `coupon` query.
…
… …

fix: Meta data type error fixed.

---

docs/toc.md
includes/class-core-schema-filters.php
includes/class-type-registry.php
includes/class-wp-graphql-woocommerce.php
includes/mutation/class-payment-method-delete.php
includes/mutation/class-payment-method-set-default.php
includes/type/interface/class-payment-token.php
includes/type/object/class-customer-type.php
includes/type/object/class-payment-token-types.php
tests/_support/Factory/PaymentTokenFactory.php
tests/_support/TestCase/WooGraphQLTestCase.php
tests/wpunit/CustomerQueriesTest.php
tests/wpunit/PaymentMethodMutationsTest.php

- Adds `availablePaymentMethods` to Customer type.
- Adds `deletePaymentMethod` mutation
- Adds `setDefaultPaymentMethod` mutation.
…
… …

feat: payment method mutations and fields implemented.

---

includes/class-type-registry.php
includes/class-wp-graphql-woocommerce.php
includes/type/object/class-country-state-type.php
includes/type/object/class-country-state.php
includes/type/object/class-root-query.php
tests/_support/Factory/ShippingZoneFactory.php
tests/wpunit/RootQueriesTest.php

- Add `allowedCountries` and `allowedCountryStates` queries for get a list of the countries and country states the WooCommerce store can sell too. See example queries below.
```graphql
query ($country: CountriesEnum!) {
allowedCountries
allowedCountryStates(country: $country) {
name
code
}
}
```
Resolves #581  …

feat: Country queries implemented.

---

includes/type/object/class-customer-type.php
tests/wpunit/CustomerQueriesTest.php

Introduces the `availablePaymentMethodsCC` and `availablePaymentMethodsEC` customer fields to complete necessary expose of child types for schema validation.
… …

fix: PaymentToken child types fixed.

---

docs/configuring-graphql-client-for-user-session.md
docs/handling-user-authentication.md
docs/handling-user-session-and-using-cart-mutations.md
docs/installation.md
docs/routing-by-uri.md
docs/settings.md
docs/using-cart-data.md
docs/using-product-data.md

Finish/cleans up documentation and while providing page meta for each doc.
…
…
- **WooGraphQL …

devops: Docs refactored heavily and provided meta data.

---

composer.json
composer.lock
includes/admin/class-general.php
includes/class-woocommerce-filters.php
includes/data/connection/class-variation-attribute-connection-resolver.php
includes/type/object/class-cart-type.php
includes/type/object/class-customer-type.php
includes/utils/class-protected-router.php
includes/utils/class-transfer-session-handler.php
tests/_data/config.php
tests/_support/Factory/ProductFactory.php
tests/_support/Factory/ProductVariationFactory.php
tests/wpunit/ProductAttributeQueriesTest.php
tests/wpunit/ProtectedRouterTest.php
tests/wpunit/TransferSessionHandlerTest.php
tests/wpunit/VariationAttributeQueriesTest.php

- Adds `accountUrl` and `accountNonce` to the Authorizing URLs option.
- Fixes issues related to auth URLs usage.
- Fixes the `simpleProduct`'s `defaultAttributes` field.
… …

feat: Account URL added to Auth URLs.

---

includes/connection/class-product-attributes.php
includes/data/connection/class-product-attribute-connection-resolver.php

- Removes `type` filtering on globalAttributes and localAtrributes
- Fixes `type` filtering on attributes
- Fixes correct data is returned for globalAttributes and localAttributes
Closes: https://github.com/wp-graphql/wp-graphql-woocommerce/issues/756
See: …

fix: localAttributes and globalAttributes filtering and returned wrong values.

---

README.txt
composer.json
composer.lock
includes/class-admin.php
includes/class-core-schema-filters.php
includes/connection/class-product-attributes.php
includes/model/class-order.php
includes/type/object/class-customer-type.php
phpcs.xml.dist
wp-graphql-woocommerce.php

This PR removes the usage of trailing commas, which throw a fatal error in PHP 7.2 and lower.
Branch is based off of https://github.com/wp-graphql/wp-graphql-woocommerce/pull/763, which should be merged first.
…
(If it’s long, please paste to https://ghostbin.com/ and insert …

fix: remove trailing commas from function calls

---

includes/admin/class-general.php
includes/connection/class-products.php
includes/connection/class-wc-terms.php
includes/data/connection/class-cart-item-connection-resolver.php
includes/data/connection/class-downloadable-item-connection-resolver.php
includes/data/connection/class-order-item-connection-resolver.php
includes/data/mutation/class-order-mutation.php
includes/model/class-order.php
includes/mutation/class-cart-add-fee.php
includes/mutation/class-cart-add-item.php
includes/mutation/class-order-create.php
includes/mutation/class-order-update.php
includes/type/object/class-customer-type.php
includes/type/object/class-meta-data-type.php
includes/type/object/class-root-query.php
includes/utils/class-transfer-session-handler.php

This PR cleans up various useless variables and unnecessary ternaries from the codebase.
Branch is based off of https://github.com/wp-graphql/wp-graphql-woocommerce/pull/763, which should be merged first.
…
(If it’s long, please paste to https://ghostbin.com/ and insert the …

fix: cleanup useless variables and ternaries

---

README.txt
composer.json
composer.lock
includes/data/connection/class-customer-connection-resolver.php
includes/mutation/class-checkout.php
phpcs.xml.dist
wp-graphql-woocommerce.php

This PR explicitly initializes arrays before they are assigned a value in the codebase.
This is a code small that can [easily lead to fatal errors](https://www.php.net/manual/en/language.types.array.php#:~:text=It%20is%20always%20better%20to%20initialize%20a%20variable%20by%20a%20direct%20assignment.) with future commits.
Branch is based off of https://github.com/wp-graphql/wp-graphql-woocommerce/pull/763, which should be merged first.
Does this close any …

fix: initialize arrays before using

---

README.txt
composer.json
composer.lock
phpcs.xml.dist
wp-graphql-woocommerce.php

This PR updates the plugin headers with the versions of PHP, WordPress, and WooCommerce that this plugin _actually_ supports. It additionally locks the stubs to those correct versions to prevent future breaking changes from leaking into the codebase accidentally.
(PHPstan was also updated to the latest version)
**Note:** This is marked as a breaking change, but technically this PR isnt actually causing any breaking behavior.
- WPGraphQL 1.14.0 (defined req) …

fix!: update version requirements to what's actually needed by code

---

includes/data/class-db-hooks.php

Removes a production call to `codecept_debug()` from the `add_cursor()` method.
This likely snuck in during debugging and can throw a fatal error when the composer `dev-dependencies` are not installed. (It slips by linters since codeception gets installed in the ci)
…
(If it’s …

fix: remove `codecept_debug()` call from production code

---

includes/data/connection/class-coupon-connection-resolver.php
includes/data/connection/class-customer-connection-resolver.php
includes/data/connection/class-order-item-connection-resolver.php
includes/data/connection/class-product-connection-resolver.php
includes/data/connection/class-shipping-method-connection-resolver.php
includes/data/connection/class-tax-rate-connection-resolver.php

This PR removes the usage of `AbstractConnectionResolver::get_offset()`, which was deprecated from WPGraphQL in v1.9.0.
Instead of `get_offset()`, we use `get_offset_for_cursor()`, and rely on the `graphql_after_cursor` and `graphql_before_cursor` query args.
Additionally, the overloaded definitions of `get_offset()` were removed from local ConnectionResolvers as their output is identical to the parent method, sans the deprecation warning.
Does this close …

dev: remove deprecated usage of `AbstractConnectionResolver::get_offset()`

---

includes/admin/class-general.php
includes/class-core-schema-filters.php
includes/data/connection/class-variation-attribute-connection-resolver.php
includes/type/interface/class-attribute.php
includes/type/interface/class-product-attribute.php
includes/type/object/class-product-attribute-types.php
includes/type/object/class-variation-attribute-type.php
includes/utils/class-transfer-session-handler.php
tests/wpunit/ProductAttributeQueriesTest.php
tests/wpunit/VariationAttributeQueriesTest.php

- Fixes inconsistency in `label` and `name` fields across different product attribute types.
- Fixes error thrown when draft product is queried by an unauthorized user.
- Fixes syntax error related to the `WPGRAPHQL_WOOCOMMERCE_ENABLE_AUTH_URLS` flag
- Stricter check added for `client_session_id` retrieval.
… …

fix: Several minor obscured syntax errors fix

---

bin/entrypoint.sh
codeception.dist.yml
docker-compose.yml
includes/class-wp-graphql-woocommerce.php
includes/connection/class-products.php
includes/connection/class-variation-attributes.php
includes/connection/class-wc-terms.php
includes/data/connection/class-product-connection-resolver.php
includes/data/connection/trait-wc-cpt-loader-common.php
includes/data/loader/class-wc-cpt-loader.php
includes/model/class-product-variation.php
includes/type/object/class-product-variation-type.php
tests/_support/Factory/ProductFactory.php
tests/_support/Factory/ProductVariationFactory.php
tests/_support/Helper/GraphQLE2E.php
tests/acceptance/CustomerProceedsToCheckoutCept.php
tests/functional/ProtectedRouterCest.php
tests/wpunit/ProductAttributeQueriesTest.php
tests/wpunit/ProductQueriesTest.php
tests/wpunit/ProductVariationQueriesTest.php
tests/wpunit/VariationAttributeQueriesTest.php

- Add support for querying variations alongside products.
- `ProductVariation.attributes` renamed to `ProductVariation.variationAttributes` to prevent collision with the `Product.attributes` field.
- **ProductConnectionResolver** class no longer deprecated.
…
(If it’s long, …

fix: ProductVariation type made to inherit the Product interface.

---

bin/_lib.sh
composer.lock
includes/data/mutation/class-customer-mutation.php
includes/mutation/class-customer-update.php
tests/_support/Factory/CustomerFactory.php
tests/wpunit/CustomerMutationsTest.php

- **updateCustomer** mutation patched to support inputs without IDs for authenticated users.
- **CustomerMutationsTest** refactored heavily.
…
…
Where has …

fix: WP User core field support fixed in `updateCustomer` mutation

---

includes/type/object/class-root-query.php

This PR fixes the `RootQuery.customer` query to default to the current user. This prevents mismatches where the user is logged in, but the `customer` is still a guest session.
The underlying issue is that the customer resolver was previously only using the existing woocommerce-session (if it exists) _or_ an explicit id passed by as an arg, but never the current authenticated user's ID. This could lead to a situation (first-time queries usually) where a user …

fix: default the resolved `customer` to the current user

---

Dockerfile
bin/_lib.sh
composer.lock
includes/data/mutation/class-cart-mutation.php

- Makes the `prepare_attributes` of the **Cart_Mutation** class a public function so it can be used in WooGraphQL Pro and other mutations utilizing the cart functionality.
… …

fix: Cart_Mutation:prepare_attributes made public

---

includes/data/connection/class-variation-attribute-connection-resolver.php

`VariationAttribute` type is now getting the `value` field from the term slug for global attributes for proper comparison with the `ProductAttribute` type `value` field.
… …

fix: VariationAttribute now sourcing value as Term slug for global attributes

---

includes/class-core-schema-filters.php
includes/class-type-registry.php
includes/class-wp-graphql-woocommerce.php
includes/connection/class-products.php
includes/type/interface/class-downloadable-products.php
includes/type/interface/class-inventoried-products.php
includes/type/interface/class-product-union.php
includes/type/interface/class-products-with-dimensions.php
includes/type/interface/class-products-with-pricing.php
includes/type/interface/class-products-with-variations.php
includes/type/object/class-product-types.php
tests/wpunit/ProductQueriesTest.php

Adds 5 new product interfaces for cleaner product queries.
- DownloadableProducts
- InventoriedProducts
- ProductsWithPricing
- ProductsWithDimensions
- ProductsWithVariations
```
query ( $id: ID!, $format: PostObjectFieldFormatEnum ) {
product(id: $id) {
id
databaseId
name
slug
date
modified
status
featured
catalogVisibility
description(format: $format)
shortDescription(format: $format)
sku
dateOnSaleFrom
dateOnSaleTo
totalSales
averageRating
reviewCount …
```

feat: Several product interfaces added.

---

includes/connection/class-products.php
includes/data/connection/class-product-connection-resolver.php
includes/model/class-product.php
includes/type/interface/class-inventoried-product.php
includes/type/object/class-root-query.php
tests/wpunit/ConnectionPaginationTest.php
tests/wpunit/RootQueriesTest.php

- Renames `allowedCountryStates` query to `countryStates`.
- Adds `countries` query for get a complete list all countries not just the one the store ships to.
- Adds the connection field `found` the product connections see example usage below
```graphql
{
products(first: 20) {
found
pageInfo {
endCursor
}
nodes {
id
}
}
}
```
The `found` field should only be resolved on the initial query from a connection without `after` or `before` cursors and will return …

feat: "found" field added to the Products Connection types

---

CHANGELOG.md
README.txt
includes/type/interface/class-cart-item.php
includes/type/interface/class-downloadable-product.php
includes/type/interface/class-inventoried-product.php
includes/type/interface/class-product-union.php
includes/type/interface/class-product-variation.php
includes/type/interface/class-product-with-attributes.php
includes/type/interface/class-product-with-dimensions.php
includes/type/interface/class-product-with-pricing.php
includes/type/interface/class-product-with-variations.php
wp-graphql-woocommerce.php

chore: version numbers set and readmes updated.

---

includes/class-type-registry.php
includes/class-wp-graphql-woocommerce.php
includes/connection/class-products.php
includes/data/connection/class-product-connection-resolver.php
includes/type/enum/class-attribute-operator-enum.php
includes/type/enum/class-product-attribute-enum.php
includes/type/input/class-collection-stats-query-input.php
includes/type/input/class-collection-stats-where-args.php
includes/type/input/class-product-attribute-filter-input.php
includes/type/object/class-collection-stats-type.php
includes/type/object/class-root-query.php
tests/wpunit/CollectionStatsQueryTest.php
tests/wpunit/ProductQueriesTest.php

Adds `collectionStats` query. Here's an example usage.
```graphql
query ($where: CollectionStatsWhereArgs){
collectionStats(
calculatePriceRange: true
calculateRatingCounts: true
calculateStockStatusCounts: true
taxonomies: [{taxonomy: PACOLOR, relation: AND}]
where: $where
) {
priceRange {
maxPrice
minPrice
}
ratingCounts {
count
}
attributeCounts {
name 
terms {
node {
slug
}
termId
count
}
}
stockStatusCounts {
status
count
}
}
}
```
Does this close any …

feat: `collectionStats` query added

---

composer.lock
includes/type/object/class-customer-type.php
tests/wpunit/CollectionStatsQueryTest.php
vendor-prefixed/firebase/php-jwt/src/BeforeValidException.php
vendor-prefixed/firebase/php-jwt/src/ExpiredException.php
vendor-prefixed/firebase/php-jwt/src/JWT.php
vendor-prefixed/firebase/php-jwt/src/JWTExceptionWithPayloadInterface.php

Prevents query from throw if guests is query payment method fields.
…
…
- …

fix: paymentMethod fields no longer throw for guest users

---

bin/_lib.sh
composer.lock
includes/class-jwt-auth-schema-filters.php
includes/type/object/class-collection-stats-type.php
wp-graphql-woocommerce.php

Updates the filters in `WPGraphQL\WooCommerce\JWT_Auth_Schema_Filters` to work with [WPGraphQL Headless Login](https://github.com/AxeWP/wp-graphql-headless-login)
… …

fix: JWT Auth hooks now support WPGraphQL Headless Login

---

includes/type/enum/class-product-attribute-enum.php

Fixes **Enum type ProductAttributeEnum must define one or more values.** error by not registering the `ProductAttributeEnum` if no product attributes exist.
… …

fix: ProductAttributeEnum given default value, if no product attributes exist

---

bin/_lib.sh
codeception.dist.yml
composer.lock
includes/data/connection/class-product-connection-resolver.php
tests/wpunit/bootstrap.php
vendor-prefixed/firebase/php-jwt/src/JWT.php

Fixes minor bug is `Product_Connection_Resolver::add_tax_query`
…
…
- …

fix: Bug fixed in Product_Connection_Resolver::add_tax_query

---

access-functions.php
includes/class-type-registry.php
includes/class-wp-graphql-woocommerce.php
includes/data/connection/class-coupon-connection-resolver.php
includes/data/connection/class-order-connection-resolver.php
includes/data/connection/class-product-connection-resolver.php
includes/data/connection/trait-wc-cpt-loader-common.php
includes/data/mutation/class-order-mutation.php
includes/mutation/class-order-create.php
includes/type/enum/class-currency-enum.php
tests/wpunit/OrderMutationsTest.php
tests/wpunit/ProductQueriesTest.php

- Fixes `currency` input field support in the `createOrder` mutation. Resolving #615 
- Fixes bug related to CPT connection sorting by meta. Adds some hooks for introducing custom sort options. Resolving #824
…
(If it’s long, please paste to https://ghostbin.com/ and insert …

fix: currency input field fixed for createOrder mutation

---

includes/type/enum/class-id-type-enums.php
includes/type/object/class-root-query.php
tests/wpunit/OrderQueriesTest.php

chore: OrderIdTypeEnum value "ORDER_NUMBER" renamed to "ORDER_KEY"

---

includes/type/object/class-downloadable-item-type.php

- Changes **DownloadableItem's** product field type to **ProductUnion** to add support for product variation. Resolves #502 
…
… …

fix: DownloadableItem "product" field type changed to ProductUnion

---

includes/utils/class-protected-router.php

- Adds `remove_filter` at the top of **Protected_Router::resolve_request()** to avoid any possible recursive triggers of the hook resulting in an infinite loop
Resolves #846  …

fix: Potential Infinite loop caused by nested `pre_get_posts` hooks patched

---

includes/class-type-registry.php
includes/class-wp-graphql-woocommerce.php
includes/connection/class-wc-terms.php
includes/type/enum/class-product-attributes-connection-orderby-enum.php

This PR adds an enum for the product attributes orderBy enum. Adding the Menu_Order to return objects in the order defined.
https://github.com/wp-graphql/wp-graphql-woocommerce/issues/475
------------------
Relevant PR: https://github.com/wp-graphql/wp-graphql/pull/3170
- **WooGraphQL Version:** 0.20.0
- **WPGraphQL Version:** 1.27.2
- **WordPress Version:** 6.6
- **WooCommerce Version:** 9.1.2

feat: Add Product_Attributes_Connection_Orderby_Enum with MENU_ORDER

---

includes/class-woocommerce-filters.php

This PR enhances the WooCommerce GraphQL functionality by adding a custom filter for handling password reset emails within the WooCommerce_Filters class. The new filter, retrieve_password_message, ensures that password reset emails are generated using the WooCommerce reset password email template.
The addition of the retrieve_password_message filter provides the following benefits:
- Consistent User Experience: Users will receive password reset emails formatted according to the WooCommerce email template, ensuring consistency with other WooCommerce communications.
- Enhanced Branding: By using WooCommerce's email template, the password reset process aligns with the overall branding and design of WooCommerce communications.
- Improved Front-End Integration: Users are directed to the …

feat: Use Woocommerce Reset Password email for ResetPassword Mutation

---

includes/type/interface/class-product-attribute.php
includes/type/object/class-product-attribute-types.php
includes/type/object/class-variation-attribute-type.php
tests/wpunit/ProductAttributeQueriesTest.php

----------------------------------------------------
Product attribute taxonomy labels are returned with all words in uppercase.
There is no need to call `ucwords` as the label is correctly saved on the database taxonomy object.
```
/var/www/html $ wp taxonomy get pa_schirmgroesse
Field         | Value                                                                                                                                                   
name          | pa_schirmgroesse                                                                                                                                        
label         | Produkt Schirmgröße in cm …
```

fix: wrong taxonomy label case in product attributes

---

.github/CODE_OF_CONDUCT.md
.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
README.txt
includes/utils/class-ql-session-handler.php
wp-graphql-woocommerce.php

chore: version numbers and READMEs updated

---

docs/configuring-graphql-client-for-user-session.md

Some typos and errors with Apollo Link examples
Fix errors on documentation
No
No
No

Fix some errors on configuring-graphql-client-for-user-session.md

---

includes/data/connection/class-product-connection-resolver.php

This pull request addresses an issue with number formatting in the maxPrice and minPrice filters for product queries in WPGraphQL WooCommerce. Previously, when users entered values greater than 999, the query failed to return the correct products due to improper formatting.
Specifically, when values over 999 were used in the `maxPrice` or `minPrice` filters, the query did not return the expected products, as demonstrated in the screenshots below.
The new …

Fix: Correct number formatting by removing unnecessary price separators

---

composer.lock
includes/class-woocommerce-filters.php
includes/data/mutation/class-checkout-mutation.php
includes/data/mutation/class-order-mutation.php
includes/model/class-order.php
tests/_support/Factory/OrderFactory.php
tests/wpunit/IntrospectionQueryTest.php

chore: General "createOrder" cleanup

---

composer.json
composer.lock
includes/connection/class-orders.php
includes/connection/class-product-attributes.php
includes/connection/class-products.php
includes/type/interface/class-downloadable-product.php
includes/type/interface/class-inventoried-product.php
includes/type/interface/class-product-union.php
includes/type/interface/class-product-variation.php
includes/type/interface/class-product-with-attributes.php
includes/type/interface/class-product-with-dimensions.php
includes/type/interface/class-product-with-pricing.php
includes/type/interface/class-product-with-variations.php
includes/type/interface/class-product.php
tests/wpunit/ProductAttributeQueriesTest.php

…re optimal schema shape
- Adds `Product` interface as parent interface to the following interfaces:
- `InventoriedProduct`
- `ProductWithPricing`
- `ProductWIthVariations`
- `DownloadableProduct`
- `ProductWithDimensions`
- `ProductWithAttributes`
- `ProductUnion`
…
(If it’s …

fix: "Product" interfaces shared fields fix

---

includes/data/connection/class-product-connection-resolver.php
tests/wpunit/ProductsQueriesTest.php

Fixes the `products` query's `where.search` parameter by replacing the `search` query clauses added by the `Automattic\WooCommerce\StoreApi\Utilities\ProductQuery` class
… …

fix: Products query "where.search" param patched

---

CHANGELOG.md
README.txt
composer.lock
wp-graphql-woocommerce.php

chore: READMEs and CHANGELOG updated

---

bin/_lib.sh
composer.lock
includes/type/object/class-meta-data-type.php
vendor-prefixed/firebase/php-jwt/src/CachedKeySet.php
vendor-prefixed/firebase/php-jwt/src/JWK.php
vendor-prefixed/firebase/php-jwt/src/JWT.php
vendor-prefixed/firebase/php-jwt/src/Key.php

fix: "key" argument for MetaData fields fixed

---

wp-graphql-woocommerce.php

fix: Bypasses Woo declare_compatiblilty call if not in plugin directory
