wp-graphql/wp-graphql-woocommerce

- src/data/connection/class-order-connection-resolver.php
Replaces `WP_Query` with `WC_Order_Query` in `order-connection-resolver.php`. This further support for custom order data stores, however implemention of the pagination will be on the developer of the data stores.
…
(If it’s long, please paste to https://ghostbin.com/ and …
> Replaces WP_Query to WC_Order_Query in Order connections

- CHANGELOG.md
- README.md
…
…
…
**Operating System:** …
**WordPress Version:** …
> CHANGELOG updated

- includes/class-actions.php
- includes/type/object/class-customer-type.php
- includes/type/object/class-product-category-type.php
- tests/wpunit/ProductQueriesTest.php
- vendor/composer/autoload_classmap.php
- vendor/composer/autoload_static.php
Adds `image` field to `ProductCategory` type
```
productCategories( where: { hideEmpty: true } ) {
nodes {
image {
...MediaItem fields
}
...ProductCategory other fields
}
}
```
…
Any other …
> Adds product category image to schema.

- includes/type/object/class-customer-type.php
Fixes a bug in web token authentication on the `Customer` type.
…
…
**Operating System:** Ubuntu …
> Fixes customer web token authentication fields

- includes/class-woocommerce-filters.php
Fixes incorrectly labelled filters related to the session handler
…
…
**Operating System:** … …
> Session header bugfix

- includes/data/connection/class-post-connection-resolver.php
Removes problematic code in the `graphql_post_object_connection_query_args` hook callback in `includes/data/class-post-connection-resolver.php`
#122 
…
Where …
> PostObject hierarchy bugfix

- includes/connection/class-products.php
- includes/data/connection/class-product-connection-resolver.php
- tests/wpunit/ProductQueriesTest.php
Fixes `Type*`, `Category*`, `Tag*` where args for product connections. Also implements a few argument name changes. 
- `CategoryName` => `Category`
- `CategoryNameIn` => `CategoryIn`
- `CategoryNameNotIn` => `CategoryNotIn`
- `Category` => `CategoryId`
- `CategoryIn` => `CategoryIdIn`
- `CategoryNotIn` => `CategoryIdNotIn`
- `TagSlugIn` => `TagIn`
- `TagSlugNotIn` => `TagNotIn`
- `TagIn` => `TagIdIn`
- `TagNotIn` => `TagIdNotIn`
Does this close any …
> Bug related to resolving product connections by taxonomies fixed.

- .travis.yml
- CHANGELOG.md
- README.txt
- composer.json
- wp-graphql-woocommerce.php
- New `orderby` fields adds added to `Product` and `Order` connections. #145 
- Product Taxonomy Hierachy #150  
- JWT Auth fields on `Customer` type #148 
- `WC_Session_Handler` collision #146 
- Filter for modifying default tax query for `product_visibility` on `Product` connections added. #142 
- `format` arg added to `desciption` fields on `Product` type. #139
…
Any …
> Release-v0.2.2

- includes/class-core-schema-filters.php
Related to WPGraphQL for ACF [#84](https://github.com/wp-graphql/wp-graphql-acf/issues/84)
#162 
… …
> Removes potential trouble filter

- CHANGELOG.md
- includes/connection/class-wc-terms.php
- includes/data/connection/class-wc-terms-connection-resolver.php
- tests/wpunit/ProductQueriesTest.php
- `Product` connections to `ProductTag` and `ProductCategory` name changed. See example below
```
query {
productBy( id: "some-id" ) {
productCategories {
nodes {
name
children {
nodes {
name
}
}
}
}
productTags {
nodes {
name
}
}
... on SimpleProduct {
productCategories {
nodes {
name
children {
nodes {
name
}
}
}
}
productTags {
nodes {
name
}
}
}
... on VariableProduct {
productCategories {
nodes {
name
children {
nodes {
name
}
}
}
}
productTags {
nodes …
```
> WPGraphQL for Custom Post Type UI taxonomy support

- includes/class-core-schema-filters.php
Add two filters the replaces all resolutions in **WPUnionTypes** that target the `Product` Interface with the `Product` child types.
…
… …
> "WPUnionType" injection filters implemented.

- includes/class-acf-schema-filters.php
- includes/class-core-schema-filters.php
- wp-graphql-woocommerce.php
- Fixes a bug related to WPGraphQL ACF
…
…
**Operating System:** Linux Mint 19.2
**WordPress …
> More support provided for WPGraphQL ACF

- includes/class-woocommerce-filters.php
`WPGraphQL\WooCommerce\WooCommerce_Filters::is_graphql_http_request()` calls replaced with `WPGraphQL\Router::is_graphql_http_request()`.
…
…
Where has this …
> local version "is_graphql_http_request" replaced with core version."

- includes/connection/class-product-attributes.php
Makes this example query possible.
```
{
products(first: 20) {
nodes {
id
name
attributes {
nodes {
id
attributeId
name
variation
}
}
}
}
}
```
…
…
Where has …
> Registers "attributes" as a "Product" field.

- includes/connection/class-cart-items.php
- includes/connection/class-coupons.php
- includes/connection/class-orders.php
- includes/type/interface/class-product.php
- wp-graphql-woocommerce.php
Stops fatal error when an unsupported product type included the query results.
#185 
…
**Operating …
> Better handling of unsupported product types.

- README.txt
- composer.json
- tests/_support/Utils/class-wc-product-advanced.php
- wp-graphql-woocommerce.php
- Improved handling of unsupported product types #199 
- Adds `cart` field to cart mutations output. #194 
- Better guest customer support #187 
- WPUnion injector added for Product types. #188 
… …
> Release v0.3.2

- includes/connection/class-products.php
- includes/data/connection/class-product-connection-resolver.php
- includes/utils/class-ql-session-handler.php
- Improves support for concurrent cart mutations by adding a transaction queue to the `QL_Session_Handler` class.
- Improves unsupported product type error handling.
… …
> Better cart mutation support/unsupported type error handling

- includes/class-jwt-auth-schema-filters.php
- includes/class-wp-graphql-woocommerce.php
- includes/connection/class-orders.php
- includes/data/mutation/class-customer-mutation.php
- includes/mutation/class-customer-register.php
- tests/wpunit/CustomerQueriesTest.php
- Removes unsecure filters from `orders` connection on the Customer type.
- Refactors `registerCustomer` to use WC's `wc_create_new_customer()`.
- Adds `customer` to `LoginPayload`. See example below.
```
mutation ($input: LoginInput!) {
login(input: $input) {
authToken
customer {
id
...customer fields
}
}
}
```
#204 
Any relevant logs, error output, GraphiQL screenshots, …
> More customer improvements.

- includes/class-jwt-auth-schema-filters.php
- Updates the WPGraphQL-JWT-Authentication filters to work with WPGraphQL v0.6.0.
…
…
**Operating …
> Adds support for the next version of WPGraphQL-JWT-Authentication

- includes/type/enum/class-id-type-enums.php
- includes/type/object/class-coupon-type.php
- tests/wpunit/IntrospectionQueryTest.php
- Fixes a bug related to the `TaxRateIdTypeEnum`
- Adds **IntrospectionQueryTest**
…
…
**Operating …
> Fixes introspection query

- includes/model/class-coupon.php
- includes/model/class-crud-cpt.php
- includes/model/class-customer.php
- includes/model/class-order-item.php
- includes/model/class-order.php
- includes/model/class-product-variation.php
- includes/model/class-product.php
- includes/model/class-refund.php
- includes/model/class-shipping-method.php
- includes/model/class-tax-rate.php
- includes/model/trait-shop-manager-caps.php
Applying PHPDoc correctly and other small changes.
> Code Improvements - Model Classes

- docs/config.js
- includes/connection/class-downloadable-items.php
- includes/data/connection/class-downloadable-item-connection-resolver.php
- tests/_support/Helper/crud-helpers/customer.php
- tests/wpunit/DownloadableItemQueriesTest.php
Adds a `DownloadableItems` connection the **Customer** type.
```
query {
customer {
downloadableItems(first: 10) {
nodes {
url
accessExpires
downloadId
downloadsRemaining
name
product {
productId
}
download {
downloadId
}
}
}
}
}
```
Closes #233 
(If it’s long, please paste to …
> Adds Customer to DownloadableItems connection

- .phpcs.xml
- README.txt
- includes/connection/class-cart-items.php
- includes/connection/class-coupons.php
- includes/connection/class-customers.php
- includes/connection/class-downloadable-items.php
- includes/connection/class-order-items.php
- includes/connection/class-orders.php
- includes/connection/class-payment-gateways.php
- includes/connection/class-posts.php
- includes/connection/class-product-attributes.php
- includes/connection/class-product-reviews.php
- includes/connection/class-products.php
- includes/connection/class-refunds.php
- includes/connection/class-shipping-methods.php
- includes/connection/class-tax-rates.php
- includes/connection/class-variation-attributes.php
- includes/connection/class-wc-terms.php
- includes/connection/common-post-type-args.php
Adding minor updates to the connection classes.
> Updates to the Connection Classes

- includes/data/mutation/class-checkout-mutation.php
- includes/mutation/class-checkout.php
- tests/wpunit/CheckoutMutationTest.php
- `customerNote` field to the `CheckoutInput` type added.
- `company` address field saving correctly
- `overwrite` address field functioning properly, and clearing old address before saving the new address provided.
…
(If it’s long, please paste to https://ghostbin.com/ and …
> Checkout mutation input fields updated

- includes/mutation/class-customer-update.php
Cleans up the `updateCustomer` resolver, and fixes #269 
…
…
**Operating System:** Linux Mint 19.2 …
> updateCustomer resolver cleaned up

- tests/wpunit/ProductQueriesTest.php
- tests/wpunit/ProductVariationQueriesTest.php
Updates tests to work with changes made in WPGraphQL v0.9.0, fixing the **Testing Integration** workflow. 
…
… …
> Adds support for changes made in WPGraphQL v0.9.0

- README.md
Updates the README links for the WooGraphQL Docs and Playground.
…
…
**Operating System:** … …
> Update some README.md links

- tests/wpunit/IntrospectionQueryTest.php
- tests/wpunit/ProductQueriesTest.php
- Updates `IntrospectionQueryTest` to test the official IntrospectionQuery provided by [GraphQL-PHP](https://github.com/webonyx/graphql-php)
- Updates `ProductQueriesTest` to work with changes made in [WPGraphQL](https://github.com/wp-graphql/wp-graphql/pull/1337)
…
(If it’s …
> Fixes some unit tests

- includes/mutation/class-review-write.php
Changes the input type of the `rating` input field on the product review mutations.
Partially Fixes #292 
… …
> Rating input type changed to "Int"

- includes/mutation/class-cart-add-item.php
- tests/wpunit/CartMutationsTest.php
- Improves error messages for the `addToCart` mutation.
- **CartMutationsTest** cleaned up and new test added.
Fixes #306 
… …
> New error handling method introduced in the "addToCart" mutation

- README.md
Adds demo and source code for examples with Next.js and Gatsby
> Adds demo/examples

- includes/type/object/class-root-query.php
Adds single product queries for all product types enabled in **WooGraphQL**.
@jacobarriola Should probably take a look at this for product bundles.
…
…
Where …
> support added for externally defined product type queries.

- docs/content/introduction.md
- docs/content/playground.md
Documentation update: using latest schema updates:
* `productId` -> `databaseId`
* product is a `node`
#347 
n/a
> [Docs]: Update sample queries with latest schema changes

- includes/type/object/class-cart-type.php
- tests/wpunit/CartQueriesTest.php
- vendor/composer/InstalledVersions.php
- vendor/composer/installed.php
Continuation of #401 by @etoler1841. I just added some testing for the change.
Closes #399 
… …
> Bugfix variations

- wp-graphql-woocommerce.php
This changes the Plugin URL header to point to the correct repo instead of an older fork of this repo.
No …
> update plugin URL to point to the actual repo

- includes/connection/class-products.php
- includes/type/object/class-cart-type.php
- Fixes reverse pagination when sorting by pricing fields
- Fixes sorting for non-root product queries.
Resolves #513 
Resolves #506
… …
> Fix: product connection sorting

- README.md
Improve installation guide
closes #532
> Update Quick Install in README.md

- bin/entrypoint.sh
- includes/utils/class-ql-session-handler.php
- tests/wpunit/QLSessionHandlerTest.php
- tests/wpunit/bootstrap.php
- Ensures that a updated session token is returned on each request a session token is provided.
- QLSessionHandlerTest added.
…
… …
> fix: QLSessionHandler behaviour changes and QLSessionHandlerTest wpunit test added

- includes/type/input/class-meta-data-input.php
- Adds optional "id" field add to "MetaDataInput" type for overwriting existing meta
…
…
- …
> feat: "id" field added to "MetaDataInput" type

- includes/type/interface/class-product-attribute.php
- includes/type/object/class-product-attribute-types.php
Makes the most fields on the ProductAttribute type nullable.
#638 
…
- …
> fix: Most product attribute fields made nullable

- includes/class-core-schema-filters.php
- includes/connection/class-customers.php
- tests/wpunit/ConnectionPaginationTest.php
- tests/wpunit/CustomerQueriesTest.php
- Customers connections model bug patched with temp fix.
Closes #592 
…
- …
> fix: temporary customers node fix applied and tested.

- includes/type/enum/class-stock-status.php
Adds a filter hook to the Stock Status Enum so that there is the ability to add custom stock statues by developers
no
-
-
- **WooGraphQL Version:** 0.11.0
- **WPGraphQL Version:** …
> feat: Add filter hook to stock status enum

- includes/type/object/class-cart-type.php
- tests/wpunit/CartQueriesTest.php
Following the default behavior, I added the option to format currency in the cart fields.
I had to change return type from null to 0 in some fields, just trying to follow the default behavior.
Not that I know
> (Query) Format currency in cart type

- wp-graphql-woocommerce.php
Updates WPGRAPHQL_WOOCOMMERCE_VERSION constant to match plugin version.
#677 
…
- **WooGraphQL …
> Updates WPGRAPHQL_WOOCOMMERCE_VERSION constant to match plugin version.

- bin/_lib.sh
- bin/cleanup.local.sh
- composer.json
- composer.lock
- docker-compose.yml
- includes/connection/class-orders.php
- includes/connection/class-products.php
- tests/_support/Factory/OrderFactory.php
- tests/wpunit/CustomerMutationsTest.php
- tests/wpunit/CustomerQueriesTest.php
Updates tests scripts and docker configurations.
…
…
- **WPGraphQL …
> devops: Test Scripts updated.

- CHANGELOG.md
- README.txt
- tests/functional/CartTransactionQueueCest.php
- wp-graphql-woocommerce.php
Pre-Release steps.
…
…
- **WordPress …
> chore: CHANGELOG.md and version numbers updated

- includes/connection/class-orders.php
…
Fixes issue with `customer {orders {...}}` for guest users
…
- …
> fix: Fixes order return type for guest.

- CHANGELOG.md
- README.txt
- wp-graphql-woocommerce.php
> CHANGELOG and version updated.

- CHANGELOG.md
- README.txt
- wp-graphql-woocommerce.php
> chore: CHANGELOG.md and version numbers updated.

- docs/toc.md
> schema link added to docs toc.

- includes/type/enum/class-orders-orderby-enum.php
- includes/type/enum/class-products-orderby-enum.php
Introducing two filters for hooking into enumeration types.
Resolves #520
…
- **WooGraphQL Version:** …
> feat: filters added to product and order orderby enumerations

- CHANGELOG.md
- README.txt
- wp-graphql-woocommerce.php
> chore: CHANGELOG and version numbers updated.

- CHANGELOG.md
> chore: Hotfix for v0.12.5

- includes/model/class-order.php
- includes/type/object/class-customer-type.php
Adds better schema support for different order types.
…
…
- **WPGraphQL …
> feat: woographql_viewable_order_types hook added

- CHANGELOG.md
> chore: CHANGELOG updated.

- CHANGELOG.md
- README.md
- README.txt
- includes/data/class-db-hooks.php
- includes/data/cursor/class-cot-cursor.php
- wp-graphql-woocommerce.php
> chore: Pre-release v0.14.0

- includes/admin/class-general.php
- Fixes `enable_authorizing_url_fields`'s `sanitize_callback`.
…
…
- …
> fix: Minor settings bug patched.

- CHANGELOG.md
- README.txt
- wp-graphql-woocommerce.php
> chore: CHANGELOG and READMEs updated.

- includes/data/mutation/class-checkout-mutation.php
> fix: Fixed shipping address getting skipped unnecessary

- CHANGELOG.md
- README.txt
- wp-graphql-woocommerce.php
> chore: version numbers, README and CHANGELOG updated.

- .gitignore
- bin/_lib.sh
- composer.json
- composer.lock
Fixes composer support by no longer nesting our prefixed dependencies in `/vendor/woographql`.
…
…
- …
> "vendor/woographql" -> "vendor-prefixed"

- .gitignore
- phpstan.neon.dist
- vendor-prefixed/firebase/php-jwt/src/BeforeValidException.php
- vendor-prefixed/firebase/php-jwt/src/CachedKeySet.php
- vendor-prefixed/firebase/php-jwt/src/ExpiredException.php
- vendor-prefixed/firebase/php-jwt/src/JWK.php
- vendor-prefixed/firebase/php-jwt/src/JWT.php
- vendor-prefixed/firebase/php-jwt/src/Key.php
- vendor-prefixed/firebase/php-jwt/src/SignatureInvalidException.php
The restored support for composer and Bedrock installation which can't run Strauss and a post install action.
…
… …
> fix: PHP-JWT versioned to maintain support for composer and WP Bedrock

- CHANGELOG.md
- README.txt
- wp-graphql-woocommerce.php
> chore: READMEs and CHANGELOG updated.

- includes/data/connection/class-product-connection-resolver.php
Removes fatal debug code from recently changed files.
…
…
- **WPGraphQL …
> chore: Fatal debug code removed

- includes/class-core-schema-filters.php
Removes old code for bypassing cart connection registration when Pro was enabled
…
…
- **WooGraphQL …
> fix: Old trouble code removed.

- includes/type/object/class-customer-type.php
- includes/utils/class-protected-router.php
- Adds hooks around the Authorizing URL hooks.
…
…
- **WPGraphQL …
> feat: Hooks added to Authorizing URL functionality

- CHANGELOG.md
- README.txt
- includes/type/enum/class-attribute-operator-enum.php
- includes/type/enum/class-product-attribute-enum.php
- includes/type/input/class-collection-stats-query-input.php
- includes/type/input/class-collection-stats-where-args.php
- includes/type/input/class-product-attribute-filter-input.php
- includes/type/object/class-collection-stats-type.php
- wp-graphql-woocommerce.php
> chore: version numbers set and CHANGELOG updated.

- CHANGELOG.md
- README.txt
- wp-graphql-woocommerce.php
> chore: version numbers updated & CHANGELOG.md updated

- CHANGELOG.md
- README.md
- README.txt
- wp-graphql-woocommerce.php
> chore: version number and READMEs updated

- CHANGELOG.md
- README.txt
- wp-graphql-woocommerce.php
> chore: READMEs & CHANGELOG updated

- includes/data/connection/class-product-connection-resolver.php
- Adds support for complex taxonomy queries by slug, resolves #822 
…
…
- …
> fix: Adds slight shim to give support for multiple category or tags by slug

- includes/class-acf-schema-filters.php
Adds support for product variation to ACF CPT resolution. Resolves #470 
…
…
- **WooGraphQL …
> fix: Support for product variations added to CPT resolution

- CHANGELOG.md
- README.txt
- includes/type/enum/class-currency-enum.php
- wp-graphql-woocommerce.php
> chore: README and CHANGELOG updated

- includes/connection/class-products.php
- tests/wpunit/ProductTaxonomyQueriesTest.php
> fix: TaxonomyToProduct connections fixed and tested

- .github/workflows/package-for-release.yml
> devops: release script updated

- includes/mutation/class-session-delete.php
- tests/wpunit/QLSessionHandlerTest.php
> chore: Minor documentation issues resolved

- .github/CONTRIBUTING.md
- bin/_lib.sh
- composer.json
- composer.lock
> devops: composer-git-hooks added. CONTRIBUTING.md updated.

- .github/workflows/package-for-release.yml
- Updates release bundler GA script.
…
…
> devops: package-for-release.yml updated

- composer.json
> devops: git hooks locked to dev environment installs

- bin/_lib.sh
- composer.lock
- includes/data/connection/class-product-connection-resolver.php
- tests/wpunit/ConnectionPaginationTest.php
- vendor-prefixed/firebase/php-jwt/src/CachedKeySet.php
- vendor-prefixed/firebase/php-jwt/src/JWK.php
- vendor-prefixed/firebase/php-jwt/src/JWT.php
- vendor-prefixed/firebase/php-jwt/src/Key.php
Fixes all known pagination issues and adds unit test for each scenario
Fixes #885 
Fixes #896
Closes #843
Closes #860 
Closes #827
…
…
> fix: "menu_order" pagination fixed
